# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IntegratorUslugPrzestrzennych
                                 A QGIS plugin
 Wtyczka umoĹĽliwia prezentacjÄ™ danych z serwisĂłw WMS, WMTS, WFS i WCS w postaci warstw w QGIS. Wtyczka wykorzystuje dane z Ewidencji ZbiorĂłw i UsĹ‚ug oraz strony geoportal.gov.pl
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-28
        copyright            : (C) 2026 by EnviroSolutions Sp. z o.o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os

PLUGIN_VERSION = ''
PLUGIN_NAME = ''

metadata_path = os.path.join(os.path.dirname(__file__), 'metadata.txt')
with open(metadata_path, 'r', encoding='utf-8') as pluginMetadataFile:
    for line in pluginMetadataFile.readlines():
        if line.startswith("version="):
            PLUGIN_VERSION = line.strip().split('=', 1)[-1]
        if line.startswith("name="):
            PLUGIN_NAME = line.strip().split('=', 1)[-1]


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IntegratorUslugPrzestrzennych class from file IntegratorUslugPrzestrzennych.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .integrator_uslug_danych_przestrzennych import IntegratorUslugPrzestrzennych
    return IntegratorUslugPrzestrzennych(iface)


