# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IntegratorPlugin
                                 A QGIS plugin
 Wtyczka umożliwia prezentację danych z serwisów WMS, WMTS, WFS i WCS w postaci warstw w QGIS. Wtyczka wykorzystuje dane z Ewidencji Zbiorów i Usług oraz strony geoportal.gov.pl
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2026 by EnviroSolutions Sp. z o.o.
        email                : gis@envirosolutions.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QToolBar
from qgis.core import Qgis, QgsSettings
from .api.add_service import AddOGCService
from .utils import QtCompat, MessageUtils, NetworkManager
from .integrator_uslug_danych_przestrzennych_dialog import IntegratorUslugPrzestrzennychDialog
from .qgis_feed import QgisFeedDialog, QgisFeed
from qgis.PyQt.QtWidgets import QDialog
import os.path

from . import PLUGIN_NAME as plugin_name
from . import PLUGIN_VERSION as plugin_version

class IntegratorUslugPrzestrzennych:
    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.settings = QgsSettings()

        if Qgis.QGIS_VERSION_INT >= 31000:
            from .qgis_feed import QgisFeed
            self.selected_industry = self.settings.value("selected_industry", None)
            show_dialog = self.settings.value("showDialog", True, type=bool)
            if self.selected_industry is None and show_dialog:
                self.showBranchSelectionDialog()
            select_indust_session = self.settings.value('selected_industry')
            self.feed = QgisFeed(selected_industry=select_indust_session, plugin_name=plugin_name)
            self.feed.initFeed()

        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.message_utils = MessageUtils()
        self.network_manager = NetworkManager()
        self.ogc_service = AddOGCService(self.network_manager)

        # initialize locale
        locale = self.settings.value('locale/userLocale')[:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', f'IntegratorPlugin_{locale}.qm'
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&EnviroSolutions')

        self.toolbar = self.iface.mainWindow().findChild(QToolBar, 'EnviroSolutions')
        if not self.toolbar:
            self.toolbar = self.iface.addToolBar(u'EnviroSolutions')
            self.toolbar.setObjectName(u'EnviroSolutions')

        self.first_start = None
        self.qt_compat = QtCompat()

    def tr(self, message):
        return QCoreApplication.translate('IntegratorUslugPrzestrzennych', message)

    def addAction(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        self.dlg = IntegratorUslugPrzestrzennychDialog()
        self.setupDialog()

        icon_path = os.path.join(self.plugin_dir, 'images', 'icon.svg')
        self.addAction(
            icon_path,
            text=self.tr(plugin_name),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        self.first_start = True
    def showBranchSelectionDialog(self):
            self.qgisfeed_dialog = QgisFeedDialog()

            if self.qgisfeed_dialog.exec_() == QDialog.Accepted:
                self.selected_branch = self.qgisfeed_dialog.comboBox.currentText()

                # Zapis w QGIS3.ini
                self.settings.setValue("selected_industry", self.selected_branch)
                self.settings.setValue("showDialog", False)
    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&EnviroSolutions'),
                action)
            # self.iface.removeToolBarIcon(action)
            self.toolbar.removeAction(action)

    def addService(self) -> None:
        successfully_add = {}
        selected_urls = self.dlg.getSelectedServicesUrls()
        for name, url in selected_urls.items():
            services = ['WFS', 'WCS'] if self.dlg.wfs_rdbtn.isChecked() else ['WMTS', 'WMS']
            service_type = self.ogc_service.detectServiceType(url, services)
            if service_type:
                if_add_layer = self.ogc_service.addService(url, service_type)
                successfully_add[name] = if_add_layer
            else:
                successfully_add[name] = False

        self.message_utils.pushInfo(self.iface, '\n'.join(
            f'Dodano usluge {key}' if value else f'Nie dodano uslugi {key}'
            for key, value in successfully_add.items()
        ))

    def setupDialog(self) -> None:
        self.dlg.add_btn.clicked.connect(self.addService)

    def run(self):
        if self.first_start:
            self.first_start = False
            self.dlg.setWindowTitle('%s %s' % (plugin_name, plugin_version))
            self.dlg.lbl_pluginVersion.setText('%s %s' % (plugin_name, plugin_version))

        self.dlg.show()
        result = self.qt_compat.execDialog(self.dlg)
        if result:
            pass


