# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WebServicePlugin
                                 A QGIS plugin
 Wtyczka umożliwia prezentację danych z serwisów WMS, WMTS, WFS i WCS w postaci warstw w QGIS. Wtyczka wykorzystuje dane z Ewidencji Zbiorów i Usług oraz strony geoportal.gov.pl
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by EnviroSolutions Sp. z o.o.
        email                : office@envirosolutions.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QToolBar

from .api.region_fetch import RegionFetch
from .api.add_service import AddOGCService
from .utils import QtCompat
# Initialize Qt resources from file resources.py
from .resources import *  # noqa: F403
# Import the code for the dialog
from .web_service_plugin_dialog import WebServicePluginDialog
import os.path

from . import PLUGIN_VERSION as plugin_version
from . import PLUGIN_NAME as plugin_name

class WebServicePlugin:
    """Wtyczka WebServicePlugin - implementacja."""

    def __init__(self, iface):
        """Constructor.

        :param iface: Interfejs QGIS, który będzie przekazywany do tej klasy.
        Umożliwia manipulację aplikacją QGIS w czasie rzeczywistym.
        Pozwala na dostęp do głównego okna QGIS i interakcję z jego elementami.
        :type iface: QgsInterface
        """
        # Zapisanie referencji do interfejsu QGIS
        self.iface = iface
        # Inicjalizacja katalogu wtyczki
        self.plugin_dir = os.path.dirname(__file__)
        # Inicjalizacja języka
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'WebServicePlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Deklaracja atrybutów instancji
        self.actions = []
        self.menu = self.tr(u'&EnviroSolutions')

        # Toolbar
        self.toolbar = self.iface.mainWindow().findChild(QToolBar, 'EnviroSolutions')
        if not self.toolbar:
            self.toolbar = self.iface.addToolBar(u'EnviroSolutions')
            self.toolbar.setObjectName(u'EnviroSolutions')

        # Sprawdzenie, czy wtyczka została uruchomiona po raz pierwszy w bieżącej sesji QGIS
        # Musi być ustawione w initGui() aby przetrwać ponowne ładowanie wtyczki
        self.first_start = None
        self.qt_compat = QtCompat()
        self.regionFetch = RegionFetch(teryt='')


    # noinspection PyMethodMayBeStatic - wyłączenie sprawdzania statycznych metod
    def tr(self, message):
        """Pobranie tłumaczenia dla stringa za pomocą API Qt.

        Implementujemy to sami, ponieważ nie dziedziczymy z QObject.

        :param message: String do tłumaczenia.
        :type message: str, QString

        :returns: Tłumaczona wersja wiadomości.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('WebServicePlugin', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Ścieżka do ikony dla tej akcji. Może być ścieżką zasobu
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Tekst, który powinien być wyświetlany w elementach menu dla tej akcji.
        :type text: str

        :param callback: Funkcja do wywołania, gdy akcja jest wyzwolona.
        :type callback: function

        :param enabled_flag: Flaga wskazująca, czy akcja powinna być domyślnie włączona
            by default. Domyślnie True.
        :type enabled_flag: bool

        :param add_to_menu: Flaga wskazująca, czy akcja powinna również
            być dodana do menu. Domyślnie True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flaga wskazująca, czy akcja powinna również
            być dodana do paska narzędzi. Domyślnie True.
        :type add_to_toolbar: bool

        :param status_tip: Opcjonalny tekst do wyświetlenia w popupie, gdy wskaźnik myszy znajduje się nad akcją.
        :type status_tip: str

        :param parent: Rodzic widgetu dla nowej akcji. Domyślnie None.
        :type parent: QWidget

        :param whats_this: Opcjonalny tekst do wyświetlenia w pasku stanu, gdy wskaźnik myszy znajduje się nad akcją.
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            # self.iface.addToolBarIcon(action)
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Utworzenie elementów menu i ikon paska narzędzi w GUI QGIS."""

        self.dlg = WebServicePluginDialog(self.regionFetch)
        self.setup_dialog()

        icon_path = ':/plugins/web_service_plugin/images/icon.svg'
        self.add_action(
            icon_path,
            text=self.tr(plugin_name),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&EnviroSolutions'),
                action)
            # self.iface.removeToolBarIcon(action)
            self.toolbar.removeAction(action)

    def add_service(self) -> None:
        successfully_add = {}
        selected_urls = self.dlg.get_selected_services_urls()
        for name, url in selected_urls.items():
            services = ['WFS', 'WCS'] if self.dlg.wfs_rdbtn.isChecked() else ['WMTS', 'WMS']
            service_type = AddOGCService.detect_service_type(url, services)
            if service_type:
                add_layer = AddOGCService.add_service(url, service_type)
                successfully_add[name] = add_layer
            else:
                successfully_add[name] = False
        info_icon = self.qt_compat.getMessageBoxIcon('Information')
        msgbox = QMessageBox(
            info_icon,
            'Informacja',
            '\n'.join(
                f'Dodano usługę {key}' if value else f'Nie dodano usługi {key}'
                for key, value in successfully_add.items()
            )
        )
        self.qt_compat.execDialog(msgbox)

    def setup_dialog(self) -> None:
        self.dlg.add_btn.clicked.connect(self.add_service)

    def run(self):
        if self.first_start:
            self.first_start = False

             # informacje o wersji
            self.dlg.setWindowTitle('%s %s' % (plugin_name, plugin_version))
            self.dlg.lbl_pluginVersion.setText('%s %s' % (plugin_name, plugin_version))

        self.dlg.show()
        result = self.qt_compat.execDialog(self.dlg)
        if result:
            pass
